Fix pyproject.toml
see https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

This fixes 
```
(.venv) pip install .
(...)
error: invalid-pyproject-build-system-requires
× Can not process file:///C:/Users/dlinke/MyProg_exp040/django-directed
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: 'poetry-core^1.0.0'

note: This is an issue with the package mentioned above, not pip.
hint: See PEP 518 for the detailed specification.
```